sudo: false

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"

env:
  matrix:
    - DJANGO="django >= 1.8, < 1.9"
    - DJANGO="django >= 1.9, < 1.10"
    - DJANGO="django >= 1.10, < 1.11"

matrix:
  include:
    - python: "3.3"
      env: DJANGO="django >= 1.8, < 1.9"

before_install:
  - pip install --upgrade pip wheel

# install dependencies
install:
  - pip install "$DJANGO"
  - pip install -r requirements.txt
  - pip install codecov coverage django-nose flake8

# lint before testing
before_script:
  - flake8 .

# run tests
script: ./manage.py test

# publish coverage reports
after_success:
  - codecov

# Send emails on failures and changes
notifications:
  email:
    on_success: change
    on_failure: always
